export default ({
  categories: [
    {id:'fruitandvegetables', name:'Frutas e Vegetais', icon:'./assets/icons/frutas.png'},
    {id:'meat', name:'Carne', icon:'./assets/icons/carne.png'},
    {id:'fish', name:'Peixe', icon:'./assets/icons/peixe.png'},
    {id:'alcohol', name:'Alcool', icon:'./assets/icons/alcool.png'},
    {id:'animals', name:'Animais', icon:'./assets/icons/animais.png'},
    {id:'drinks', name:'Bebidas', icon:'./assets/icons/bebidas.png'},
    {id:'teaandcoffee', name:'Chá e Café', icon:'./assets/icons/chaecafe.png'},
    {id:'charcutarie', name:'Charcutaria', icon:'./assets/icons/charcutaria.png'},
    {id:'frozen', name:'Congelados', icon:'./assets/icons/congelados.png'},
    {id:'hygieneandbeauty', name:'Higiene e Beleza', icon:'./assets/icons/higieneebeleza.png'},
    {id:'dairy', name:'Laticínios', icon:'./assets/icons/laticinios.png'},
    {id:'groceries', name:'Mercearia', icon:'./assets/icons/mercearia.png'},
    {id:'bread', name:'Padaria', icon:'./assets/icons/padaria.png'},
    {id:'baby', name:'Para o bebé', icon:'./assets/icons/paraobebe.png'},
    {id:'homegoods', name:'Para o lar', icon:'./assets/icons/paraolar.png'},
    {id:'takeaway', name:'Pronto a comer', icon:'./assets/icons/prontoacomer.png'},
  ],
  banner:[
    {bannerid:'firstbanner', bannerimage:'./banners.png'}
  ],

  stores: [
    {id:'continente', name:'Continente', icon:'./assets/supermarkets/continente.png', discountsNumber: 500},
    {id:'pingodoce', name:'Pingo Doce', icon:'./assets/supermarkets/pingodoce.png', discountsNumber:500},
    {id:'lidl', name:'Lidl', icon:'./assets/supermarkets/lidl.png', discountsNumber:500},
    {id:'auchan', name:'Auchan', icon:'./assets/supermarkets/auchan.png', discountsNumber:500},
    {id:'aldi', name:'Aldi', icon:'./assets/supermarkets/aldi.png', discountsNumber:500},
    {id:'intermache', name:'Intermaché', icon:'./assets/supermarkets/intermache.png', discountsNumber:500},
    {id:'minipreco', name:'Mini Preço', icon:'./assets/supermarkets/minipreco.png', discountsNumber:500},
  ],
  stories: [
    {id:'firsttip', name:'Guia de Ervas Aromaticas', firstImage:'./assets/tipsandrecepies/firsttip.png'},
    {id:'secondtip', name:'Ervas em Azeite', firstImage:'./assets/tipsandrecepies/secondtip.png'},
    {id:'thirdtip', name:'Como conservar as ervas', firstImage:'./assets/tipsandrecepies/third.png'},
    {id:'forthtip', name:'5 receitas de ovos', firstImage:'./assets/tipsandrecepies/forth.png'},
    {id:'fifthtip', name:'Batata com crosta', firstImage:'./assets/tipsandrecepies/fifth.png'},
  ],
  flyers: [
    {id:'continente', name:'Continente', flyerFirstImage:'./assets/flyers/folhetocontinente.png', flyersNumber: 1},
    {id:'pingodoce', name:'Pingo Doce', flyerFirstImage:'./assets/flyers/folhetopingodoce.png', flyersflyersNumber:1},
    {id:'lidl', name:'Lidl', flyerFirstImage:'./assets/flyers/folhetolidl.png', flyersNumber:1},
    {id:'auchan', name:'Auchan', flyerFirstImage:'./assets/flyers/folhetoauchan.png', flyersNumber:1},
    {id:'aldi', name:'Aldi', flyerFirstImage:'./assets/flyers/folhetoaldi.png', flyersNumber:1},
    {id:'intermache', name:'Intermaché', flyerFirstImage:'./assets/flyers/folhetointermache.png', flyersNumber:1},
    {id:'minipreco', name:'Mini Preço', flyerFirstImage:'./assets/flyers/folhetominipreco.png', flyersNumber:1},
  ],
  products: [
    {id:'banana', category:'fruitandvegetables', name:'Banana', untilDate:'31 de Abril', productUnits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'0.89', icon:'/assets/products/banana.png'},
    {id:'petitgateau', category:'frozen', name:'Petit Gateau Chocolate Negro Pingo Doce 320 gr', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'1.89', icon:'/assets/products/petitgateau.png'},
    {id:'brocolos', category:'fruitandvegetables', name:'Brocolos', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'2.49', icon:'/assets/products/brocolos.png'},
    {id:'limao', category:'fruitandvegetables', name:'Limão', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'1.39', icon:'/assets/products/limao.png'},
    {id:'peitodefrango', category:'meat', name:'Peito de Frango', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'0.49', icon:'/assets/products/peitodefrango.png'},
    {id:'salmao', category:'fish', name:'Salmão', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'5.89', icon:'/assets/products/salmao.png'},
    {id:'vodka', category:'alcohol', name:'Vodka Smirnoff', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'0.11', icon:'/assets/products/vodkasmirnoff.png'},
    {id:'alimentosecoultima7kg', category:'animals', name:'Alimento Seco Royal Canin 5kg Sabor Borrego', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'0.75', icon:'/assets/products/alimentosecocao.png'},
  ],
})
