export default ({
  categories: [
    {id:'fruitandvegetables', name:'Frutas e Vegetais', icon:'./frutas.png'},
    {id:'meat', name:'Carne', icon:'./carne.png'},
    {id:'fish', name:'Peixe', icon:'./peixe.png'},
    {id:'alcohol', name:'Alcool', icon:'./alcool.png'},
    {id:'animals', name:'Animais', icon:'./animais.png'},
    {id:'drinks', name:'Bebidas', icon:'./bebidas.png'},
    {id:'teaandcoffee', name:'Chá e Café', icon:'./chaecafe.png'},
    {id:'charcutarie', name:'Charcutaria', icon:'./charcutaria.png'},
    {id:'frozen', name:'Congelados', icon:'./congelados.png'},
    {id:'hygieneandbeauty', name:'Higiene e Beleza', icon:'./higieneebeleza.png'},
    {id:'dairy', name:'Laticínios', icon:'./laticinios.png'},
    {id:'groceries', name:'Mercearia', icon:'./mercearia.png'},
    {id:'bread', name:'Padaria', icon:'./padaria.png'},
    {id:'baby', name:'Para o bebé', icon:'./paraobebe.png'},
    {id:'homegoods', name:'Para o lar', icon:'./paraolar.png'},
    {id:'takeaway', name:'Pronto a comer', icon:'./prontoacomer.png'},
  ],
  banner:[
    {bannerid:'firstbanner', bannerimage:'./banners.png'}
  ],

  stores: [
    {id:'continente', name:'Continente', icon:'./continente.png', discountsNumber: 500},
    {id:'pingodoce', name:'Pingo Doce', icon:'./pingodoce.png', discountsNumber:500},
    {id:'lidl', name:'Lidl', icon:'./lidl.png', discountsNumber:500},
    {id:'auchan', name:'Auchan', icon:'./auchan.png', discountsNumber:500},
    {id:'aldi', name:'Aldi', icon:'./aldi.png', discountsNumber:500},
    {id:'intermache', name:'Intermaché', icon:'./intermache.png', discountsNumber:500},
    {id:'minipreco', name:'Mini Preço', icon:'./minipreco.png', discountsNumber:500},
  ],
  stories: [
    {id:'firsttip', name:'Guia de Ervas Aromaticas', firstImage:'./firsttip.png'},
    {id:'secondtip', name:'Ervas em Azeite', firstImage:'./secondtip.png'},
    {id:'thirdtip', name:'Como conservar as ervas', firstImage:'./third.png'},
    {id:'forthtip', name:'5 receitas de ovos', firstImage:'./forth.png'},
    {id:'fifthtip', name:'Batata com crosta', firstImage:'./fifth.png'},
  ],
  flyers: [
    {id:'continente', name:'Continente', flyerFirstImage:'./folhetocontinente.png', flyersNumber: 1},
    {id:'pingodoce', name:'Pingo Doce', flyerFirstImage:'./folhetopingodoce.png', flyersflyersNumber:1},
    {id:'lidl', name:'Lidl', flyerFirstImage:'./folhetolidl.png', flyersNumber:1},
    {id:'auchan', name:'Auchan', flyerFirstImage:'./folhetoauchan.png', flyersNumber:1},
    {id:'aldi', name:'Aldi', flyerFirstImage:'./folhetoaldi.png', flyersNumber:1},
    {id:'intermache', name:'Intermaché', flyerFirstImage:'./folhetointermache.png', flyersNumber:1},
    {id:'minipreco', name:'Mini Preço', flyerFirstImage:'./folhetominipreco.png', flyersNumber:1},
  ],
  products: [
    {id:'banana', category:'fruitandvegetables', name:'Banana', untilDate:'31 de Abril', productUnits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'0.89', icon:'./banana.png'},
    {id:'petitgateau', category:'frozen', name:'Petit Gateau Chocolate Negro Pingo Doce 320 gr', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'1.89', icon:'./petitgateau.png'},
    {id:'brocolos', category:'fruitandvegetables', name:'Brocolos', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'2.49', icon:'./brocolos.png'},
    {id:'limao', category:'fruitandvegetables', name:'Limão', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'1.39', icon:'./limao.png'},
    {id:'peitodefrango', category:'meat', name:'Peito de Frango', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'0.49', icon:'./peitodefrango.png'},
    {id:'salmao', category:'fish', name:'Salmão', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'5.89', icon:'./salmao.png'},
    {id:'vodka', category:'alcohol', name:'Vodka Smirnoff', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'0.11', icon:'./vodkasmirnoff.png'},
    {id:'alimentosecoultima7kg', category:'animals', name:'Alimento Seco Royal Canin 5kg Sabor Borrego', untilDate:'31 de Abril', productunits:'1 kg', pricePerUnit:'0.89', oldProductPrice:'1', newProductPrice:'0.75', icon:'./alimentosecocao.png'},
  ],
})
